model:
  channels: 32
  num_blocks: 7
  semantic_classes: 20
  instance_classes: 18
  sem2ins_classes: []
  semantic_only: False
  ignore_label: -100
  transformer_cfg:
    n_context_points: 4096
    n_queries: 256
    dec_dim: 64
    dec_ffn_dim: 256
    dec_nhead: 8
    dec_nlayers: 6
    n_subsample: 40000

  grouping_cfg:
    sem_inst_cls_thresh: 0.3
    iou_thresh: 0.2
    score_thr: 0.2
    radius: 0.04
    mean_active: 300
    mean_active_nmc: 100
    class_numpoint_mean: [-1., -1., 3917., 12056., 2303.,
                          8331., 3948., 3166., 5629., 11719.,
                          1003., 3317., 4912., 10221., 3889.,
                          4136., 2120., 945., 3967., 2589.]
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: [0, 1]
  instance_voxel_cfg:
    scale: 50
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 400
    pos_iou_thr: 0.5
    focal_loss: False
    dice_loss: False
  test_cfg:
    x4_split: False
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
  fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear', 'offset_vertices_linear', 'box_conf_linear']
  # fixed_modules: []
  # embedding_coord: False//
  
data:
  train:
    type: 'scannetv2'
    data_root: 'dataset/scannetv2'
    prefix: 'train'
    suffix: '_inst_nostuff.pth'
    training: True
    repeat: 4
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 'scannetv2'
    data_root: 'dataset/scannetv2'
    prefix: 'val'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 50
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000


dataloader:
  train:
    batch_size: 10
    num_workers: 4
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.002

save_cfg:
  semantic: False
  offset: False
  instance: False
  offset_vertices: False
  nmc_clusters: False

fp16: True
epochs: 40
step_epoch: 25
save_freq: 4
pretrain: 'pretrains/best_pretrain_bbox_context_iou_conf_no_coord_embed.pth'
work_dir: ''
